--------------------------------------------------------------------------------
-- SMART HOME APPLIANCES - ORACLE 11g DB SCRIPT
-- Module: USERSLOGIN (application users / authentication)
-- Convention: status      = 0 (Active)    | 1 (Inactive / Soft-Deleted)
--             loginstatus = 0 (Logged Out) | 1 (Logged In)
--             createdby / editby = '<user> | <DD-MON-YYYY HH24:MI:SS>'
--
-- IMPORTANT: password is ALWAYS a bcrypt hash generated by the Node app
-- (bcrypt.hash). Oracle 11g has no native bcrypt, so hashing must never
-- happen in SQL — the app sends an already-hashed string, and this
-- script only ever stores/compares that string. Plaintext passwords
-- must never reach these procedures.
--------------------------------------------------------------------------------

SET DEFINE OFF;

--================================================================================
-- 1. SEQUENCE
--================================================================================
CREATE SEQUENCE seq_userslogin START WITH 1 INCREMENT BY 1 NOCACHE NOCYCLE;


--================================================================================
-- 2. TABLE
--================================================================================
CREATE TABLE userslogin
(
  userid       INTEGER        NOT NULL,
  username     VARCHAR2(80)   NOT NULL,
  password     VARCHAR2(200)  NOT NULL,           -- bcrypt hash (~60 chars), sized with headroom
  status       NUMBER(1,0)    DEFAULT 0 NOT NULL,  -- 0 Active | 1 Inactive
  loginstatus  NUMBER(1,0)    DEFAULT 0 NOT NULL,  -- 0 Logged Out | 1 Logged In
  userrole     VARCHAR2(30)   DEFAULT 'USER' NOT NULL,
  createdby    VARCHAR2(80),
  editby       VARCHAR2(80),
  CONSTRAINT pk_userslogin PRIMARY KEY (userid)
);


--================================================================================
-- 3. INDEXING
--================================================================================
CREATE UNIQUE INDEX uk_userslogin_username ON userslogin (UPPER(username));
CREATE INDEX idx_userslogin_status         ON userslogin (status);


--================================================================================
-- 4. PROCEDURES
--================================================================================

-- ---------- ADD / EDIT (admin user management) ----------
-- vpassword is OPTIONAL here: pass NULL on edit to leave the password
-- untouched. Password changes should normally go through change_password
-- below (self-service, current-password verified in the app layer first).
CREATE OR REPLACE PROCEDURE add_edit_user
(
  vuserid     IN NUMBER,
  vusername   IN VARCHAR2,
  vpassword   IN VARCHAR2,   -- bcrypt hash, or NULL to keep current on edit
  vuserrole   IN VARCHAR2,
  vstatus     IN NUMBER,
  vcreatedby  IN VARCHAR2,
  vmessage   OUT VARCHAR2
)
AS
  IsExist       NUMBER;
  DupExist      NUMBER;
  cur_username  userslogin.username%TYPE;
  cur_password  userslogin.password%TYPE;
  cur_userrole  userslogin.userrole%TYPE;
  cur_status    userslogin.status%TYPE;
  eff_username  userslogin.username%TYPE;
  eff_password  userslogin.password%TYPE;
  eff_userrole  userslogin.userrole%TYPE;
  eff_status    userslogin.status%TYPE;
BEGIN
  IF vuserid IS NULL THEN
    IsExist := 0;
  ELSE
    SELECT COUNT(*) INTO IsExist FROM userslogin WHERE userid = vuserid;
  END IF;

  IF IsExist = 1 THEN
    SELECT username, password, userrole, status
      INTO cur_username, cur_password, cur_userrole, cur_status
      FROM userslogin
     WHERE userid = vuserid;
  END IF;

  eff_username := NVL(vusername, cur_username);
  eff_password := NVL(vpassword, cur_password);
  eff_userrole := NVL(vuserrole, NVL(cur_userrole, 'USER'));
  eff_status   := NVL(vstatus, cur_status);

  -- New user must always come with a password hash
  IF IsExist = 0 AND vpassword IS NULL THEN
    vmessage := 'Password Is Required For New User';
    RETURN;
  END IF;

  -- Duplicate username check (excluding self on edit)
  SELECT COUNT(*) INTO DupExist
    FROM userslogin
   WHERE UPPER(username) = UPPER(eff_username)
     AND (vuserid IS NULL OR userid <> vuserid);

  IF DupExist > 0 THEN
    vmessage := 'Username Already Exists';
    RETURN;
  END IF;

  IF IsExist = 0 THEN
    INSERT INTO userslogin (userid, username, password, status, loginstatus, userrole, createdby)
    VALUES (seq_userslogin.NEXTVAL, vusername, vpassword, NVL(vstatus, 0), 0, NVL(vuserrole, 'USER'),
            vcreatedby || ' | ' || TO_CHAR(currentdatetime(), 'DD-MON-YYYY HH24:MI:SS'));
    vmessage := 'Successfully Inserted';
  ELSE
    UPDATE userslogin
       SET username = eff_username,
           password = eff_password,
           userrole = eff_userrole,
           status   = eff_status,
           editby   = vcreatedby || ' | ' || TO_CHAR(currentdatetime(), 'DD-MON-YYYY HH24:MI:SS')
     WHERE userid = vuserid;
    vmessage := 'Successfully Updated';
  END IF;
  COMMIT;
EXCEPTION
  WHEN DUP_VAL_ON_INDEX THEN
    ROLLBACK;
    vmessage := 'Duplicate Entry';
  WHEN OTHERS THEN
    ROLLBACK;
    vmessage := 'Error in Modification';
    RAISE;
END;
/

-- ---------- GET (list, default: only active, status = 0) ----------
-- Deliberately excludes the password column — this is for admin listing
-- screens, never for authentication.
CREATE OR REPLACE PROCEDURE get_users
(
  vcursor   OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN vcursor FOR
    SELECT userid, username, status, loginstatus, userrole, createdby, editby
      FROM userslogin
     WHERE status = 0
     ORDER BY username;
END;
/

-- ---------- GET SINGLE USER BY USERNAME (for login only) ----------
-- Includes the password hash. Only ever called from the login flow —
-- never returned to the client as-is.
CREATE OR REPLACE PROCEDURE get_user_by_username
(
  vusername   IN  VARCHAR2,
  vcursor     OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN vcursor FOR
    SELECT userid, username, password, status, loginstatus, userrole
      FROM userslogin
     WHERE UPPER(username) = UPPER(vusername);
END;
/

-- ---------- GET SINGLE USER BY ID (for change-password flow) ----------
CREATE OR REPLACE PROCEDURE get_user_by_id
(
  vuserid   IN  NUMBER,
  vcursor   OUT SYS_REFCURSOR
)
AS
BEGIN
  OPEN vcursor FOR
    SELECT userid, username, password, status, loginstatus, userrole
      FROM userslogin
     WHERE userid = vuserid;
END;
/

-- ---------- CHANGE PASSWORD (self-service) ----------
-- The app must verify the user's current password (bcrypt.compare)
-- BEFORE calling this — this procedure just persists the new hash.
CREATE OR REPLACE PROCEDURE change_password
(
  vuserid     IN NUMBER,
  vpassword   IN VARCHAR2,   -- new bcrypt hash
  vcreatedby  IN VARCHAR2,
  vmessage   OUT VARCHAR2
)
AS
BEGIN
  IF vpassword IS NULL THEN
    vmessage := 'Password Is Required';
    RETURN;
  END IF;

  UPDATE userslogin
     SET password = vpassword,
         editby   = vcreatedby || ' | ' || TO_CHAR(currentdatetime(), 'DD-MON-YYYY HH24:MI:SS')
   WHERE userid = vuserid;

  IF SQL%ROWCOUNT = 0 THEN
    vmessage := 'Record Not Found';
  ELSE
    vmessage := 'Password Changed Successfully';
  END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    vmessage := 'Error in Modification';
    RAISE;
END;
/

-- ---------- SET LOGIN STATUS (on successful login / on logout) ----------
CREATE OR REPLACE PROCEDURE set_login_status
(
  vuserid       IN NUMBER,
  vloginstatus  IN NUMBER,
  vmessage     OUT VARCHAR2
)
AS
BEGIN
  UPDATE userslogin
     SET loginstatus = vloginstatus
   WHERE userid = vuserid;

  IF SQL%ROWCOUNT = 0 THEN
    vmessage := 'Record Not Found';
  ELSE
    vmessage := 'Successfully Updated';
  END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    vmessage := 'Error in Modification';
    RAISE;
END;
/

-- ---------- SOFT DELETE ----------
CREATE OR REPLACE PROCEDURE delete_user
(
  vuserid     IN NUMBER,
  vcreatedby  IN VARCHAR2,
  vmessage   OUT VARCHAR2
)
AS
BEGIN
  UPDATE userslogin
     SET status = 1,
         editby = vcreatedby || ' | ' || TO_CHAR(currentdatetime(), 'DD-MON-YYYY HH24:MI:SS')
   WHERE userid = vuserid;

  IF SQL%ROWCOUNT = 0 THEN
    vmessage := 'Record Not Found';
  ELSE
    vmessage := 'Successfully Deleted';
  END IF;
  COMMIT;
EXCEPTION
  WHEN OTHERS THEN
    ROLLBACK;
    vmessage := 'Error in Modification';
    RAISE;
END;
/
